In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

#### Load the data

- auto data

In [30]:
location = "https://github.com/gridflowai/gridflowAI-datasets-icons/raw/master/AI-DATASETS/01-MISC/auto-mpg.csv"

In [32]:
df = pd.read_csv(location)

In [33]:
df.shape

(398, 9)

In [36]:
df.sample(5)

mpg  cylinders  displacement horsepower  weight  acceleration  \
111  18.0          3          70.0         90    2124          13.5   
21   24.0          4         107.0         90    2430          14.5   
36   19.0          6         250.0         88    3302          15.5   
57   24.0          4         113.0         95    2278          15.5   
234  24.5          4         151.0         88    2740          16.0   

     model year  origin               car name  
111          73       3              maxda rx3  
21           70       2            audi 100 ls  
36           71       1        ford torino 500  
57           72       3  toyota corona hardtop  
234          77       1  pontiac sunbird coupe

In [38]:
df.drop(['car name'], axis=1, inplace=True)

In [40]:
df.sample(5)

mpg  cylinders  displacement horsepower  weight  acceleration  \
160  17.0          6         231.0        110    3907          21.0   
97   18.0          6         225.0        105    3121          16.5   
261  18.1          6         258.0        120    3410          15.1   
149  24.0          4         120.0         97    2489          15.0   
169  20.0          6         232.0        100    2914          16.0   

     model year  origin  
160          75       1  
97           73       1  
261          78       1  
149          74       3  
169          75       1

In [55]:
X = df.drop(['mpg'], axis=1)
y = df['mpg']

I - (import the ML library)

In [79]:
from sklearn.linear_model import LinearRegression

I - (Instantiate the model)

In [81]:
linreg = LinearRegression()

F - (fit the data  to the model, train the model)

In [84]:
linreg.fit(X, y)

ValueError: could not convert string to float: '?'

#### Please do data clean-up

check for missing values

In [88]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
dtype: int64

In [90]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
dtype: object

In [92]:
df[['horsepower']]

horsepower
0          130
1          165
2          150
3          150
4          140
..         ...
393         86
394         52
395         84
396         79
397         82

[398 rows x 1 columns]

In [96]:
np.unique(df.horsepower, return_counts=True)

(array(['100', '102', '103', '105', '107', '108', '110', '112', '113',
        '115', '116', '120', '122', '125', '129', '130', '132', '133',
        '135', '137', '138', '139', '140', '142', '145', '148', '149',
        '150', '152', '153', '155', '158', '160', '165', '167', '170',
        '175', '180', '190', '193', '198', '200', '208', '210', '215',
        '220', '225', '230', '46', '48', '49', '52', '53', '54', '58',
        '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70',
        '71', '72', '74', '75', '76', '77', '78', '79', '80', '81', '82',
        '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93',
        '94', '95', '96', '97', '98', '?'], dtype=object),
 array([17,  1,  1, 12,  1,  1, 18,  3,  1,  5,  1,  4,  1,  3,  2,  5,  1,
         1,  1,  1,  1,  2,  7,  1,  7,  1,  1, 22,  1,  2,  2,  1,  2,  4,
         1,  5,  5,  5,  3,  1,  2,  1,  1,  1,  3,  1,  3,  1,  2,  3,  1,
         4,  2,  1,  2,  5,  1,  2,  3,  1, 10,  1, 12,  6,  3, 1

In [100]:
df[df['horsepower'] == '?']

mpg  cylinders  displacement horsepower  weight  acceleration  \
32   25.0          4          98.0          ?    2046          19.0   
126  21.0          6         200.0          ?    2875          17.0   
330  40.9          4          85.0          ?    1835          17.3   
336  23.6          4         140.0          ?    2905          14.3   
354  34.5          4         100.0          ?    2320          15.8   
374  23.0          4         151.0          ?    3035          20.5   

     model year  origin  
32           71       1  
126          74       1  
330          80       2  
336          80       1  
354          81       2  
374          82       1

let us remove the rows where the horsepower = '?'

In [110]:
indx_with_qs_mark = df[df['horsepower'] == '?'].index
indx_with_qs_mark

Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [114]:
df_without_qs_mark = df.drop(indx_with_qs_mark, axis=0)

In [118]:
df_without_qs_mark[df_without_qs_mark['horsepower'] == '?']

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model year, origin]
Index: []

In [120]:
X = df_without_qs_mark.drop(['mpg'], axis=1)
y = df_without_qs_mark['mpg']

In [126]:
linreg = LinearRegression()

In [127]:
linreg.fit(X, y)

LinearRegression()

In [131]:
linreg.coef_                  # m1, m2, m3

array([-0.49337632,  0.01989564, -0.01695114, -0.00647404,  0.08057584,
        0.75077268,  1.4261405 ])

In [134]:
linreg.intercept_             # C 

-17.218434622017522

In [137]:
new_data = [[10, 5, 6,10, 5, 6,6]]

In [140]:
linreg.predict(new_data)

D:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-8.75480866])